### ISSUE TITLE
Pull information about quiz participation

### ISSUE THREAD

**Issue by kirstykitto** [uts-cic/Canvas-Data-Aggregator#2]
Pull in information about student participation in quizzes that can be used to build aggregated report about student completion of formative activities (i.e. activities not in the gradebook).

**Comment by kirstykitto** [comment]
Keep in mind that there are quite a few types of quizzes available: https://community.canvaslms.com/docs/DOC-10706

**Comment by DezeG** [comment]
Quizzes support has been added.
However, Canvas API statistics is not detailed enough.
I think it requires additional aggregation with some programming languages, not script.
Priority languages:
1. C for initial tests
2. JavaScript for a final solution.

**Comment by DezeG** [comment]
Decided to keep it away from the script and implement it separately.
