### ISSUE TITLE
Some discussion threads missing 

### ISSUE THREAD

**Issue by kirstykitto** [uts-cic/Canvas-Data-Aggregator#3]
One of my classes from last semester is missing threads. There were a lot of discussions created there so it may be a time out issue... Try testing with some more of these types of subjects to see if it can be replicated.

**Comment by DezeG** [comment]
I would ask to try to pull data with a new version of script and provide me feedback according t this issue

**Comment by DezeG** [comment]
By default, canvas returns 10 instances
Fixed with parameter per_page=100
